assetic:
    assets:
        # admin assets
        nyrocms_js_admin:
            inputs:
                - '@NyroDevNyroCmsBundle/Resources/public/js/admin/*.js'
                - '@NyroDevUtilityBundle/Resources/public/js/*_tinymce.js'
                - '@NyroDevUtilityBundle/Resources/public/js/*_admin.js'
                - '@NyroDevUtilityBundle/Resources/public/js/autocomplete/50_autocomplete.js'
        nyrocms_css_admin:
            inputs:
                - '@NyroDevUtilityBundle/Resources/public/css/*_admin.css'
                - '@NyroDevNyroCmsBundle/Resources/public/css/admin/*.css'
        nyrocms_js_admin_composer:
            inputs:
                - '@NyroDevNyroCmsBundle/Resources/public/js/admin/001_jquery.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/admin/100_jquery-ui.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/admin/150_svg4everybody.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/admin/200_jquery.nyroModal.custom.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/admin/400_utils.js'
                - '@NyroDevUtilityBundle/Resources/public/js/*_tinymce.js'
                - '@NyroDevUtilityBundle/Resources/public/js/plupload/*.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/public/200_utilities.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/public/501_slideshow.js'
                - '@NyroDevNyroCmsBundle/Resources/public/js/composer/*.js'
        nyrocms_css_admin_composer:
            inputs:
                - '@NyroDevUtilityBundle/Resources/public/css/*_admin.css'
                - '@NyroDevUtilityBundle/Resources/public/css/plupload.css'
                - '@NyroDevNyroCmsBundle/Resources/public/css/admin/000_fonts.css'
                - '@NyroDevNyroCmsBundle/Resources/public/css/admin/100_jquery-ui.css'
                - '@NyroDevNyroCmsBundle/Resources/public/css/admin/200_nyroModal.css'
                - '@NyroDevNyroCmsBundle/Resources/public/css/composer/*.css'