services:
    NyroDev\NyroCmsBundle\Form\Type\UserFilterType:
        alias: nyrocms.userFilter.form.type:
        arguments: ['@service_container']
        tags:
          - { name: form.type }

    NyroDev\NyroCmsBundle\Form\Type\ContentHandlerFilterType:
        alias: nyrocms.contentHandlerFilter.form.type:
        arguments: ['@service_container']
        tags:
          - { name: form.type }

    NyroDev\NyroCmsBundle\Form\Type\ContactType:
        alias: nyrocms.handler.contact.form.type:
        arguments: ['@service_container']
        tags:
          - { name: form.type }
    
    NyroDev\NyroCmsBundle\Form\Type\ContactMessageFilterType:
        alias: nyrocms.handler.contactMessageFilter.form.type:
        arguments: ['@service_container']
        tags:
          - { name: form.type }
    
    NyroDev\NyroCmsBundle\Form\Extension\FileTypeExtension:
        alias: nyrocms.file_extension.form.type:
        arguments: ['@nyrocms']
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }