services:
    NyroDev\NyroCmsBundle\Form\Type\UserFilterType:
        arguments: ['@service_container']
        tags:
          - { name: form.type }

    NyroDev\NyroCmsBundle\Form\Type\ContentHandlerFilterType:
        arguments: ['@service_container']
        tags:
          - { name: form.type }

    NyroDev\NyroCmsBundle\Form\Type\ContactType:
        arguments: ['@service_container']
        tags:
          - { name: form.type }
    
    NyroDev\NyroCmsBundle\Form\Type\ContactMessageFilterType:
        arguments: ['@service_container']
        tags:
          - { name: form.type }
    
    NyroDev\NyroCmsBundle\Form\Extension\FileTypeExtension:
        arguments: ['@nyrocms']
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }