services:
    NyroDev\NyroCmsBundle\Form\Type\UserFilterType:
        calls:
          - [setContainerInterface, ['@Psr\Container\ContainerInterface']]
        tags:
          - { name: form.type }

    NyroDev\NyroCmsBundle\Form\Type\ContentHandlerFilterType:
        calls:
          - [setContainerInterface, ['@Psr\Container\ContainerInterface']]
        tags:
          - { name: form.type }

    NyroDev\NyroCmsBundle\Form\Type\ContactType:
        calls:
          - [setContainerInterface, ['@Psr\Container\ContainerInterface']]
        tags:
          - { name: form.type }
    
    NyroDev\NyroCmsBundle\Form\Type\ContactMessageFilterType:
        calls:
          - [setContainerInterface, ['@Psr\Container\ContainerInterface']]
        tags:
          - { name: form.type }
    
    NyroDev\NyroCmsBundle\Form\Extension\FileTypeExtension:
        arguments: ['@nyrocms']
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }