parameters:
    nyrocms.form.userFilter.class: NyroDev\NyroCmsBundle\Form\Type\UserFilterType

services:
    nyrocms.userFilter.form.type:
        class: %nyrocms.form.userFilter.class%
        arguments: ['@service_container']
        tags:
          - { name: form.type }
    nyrocms.file_extension.form.type:
        class: NyroDev\NyroCmsBundle\Form\Extension\FileTypeExtension
        arguments: ['@nyrocms']
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }