nyrocms_admin_homepage:
    path: /
    defaults: { _controller: NyroDevNyroCmsBundle:Admin:index }

nyrocms_admin_login:
    path: /login
    defaults: { _controller: NyroDevNyroCmsBundle:Admin:login }

nyrocms_admin_forgot:
    path: /forgot/{id}/{key}
    defaults: { _controller: NyroDevNyroCmsBundle:Admin:forgot, id: null, key: null }

nyrocms_admin_welcome:
    path: /welcome/{id}/{key}
    defaults: { _controller: NyroDevNyroCmsBundle:Admin:forgot, welcome: true }

nyrocms_admin_account:
    path: /account
    defaults: { _controller: NyroDevNyroCmsBundle:Admin:account }

nyrocms_admin_switch_rootContent:
    path: /switchRootContent/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminTpl:switchRootContent }

nyrocms_admin_cc:
    path: /cc
    defaults: { _controller: NyroDevNyroCmsBundle:Admin:cc }

nyrocms_admin_security_check:
    path: /login_check

nyrocms_admin_security_logout:
    path: /logout

nyrocms_admin_tinymce_browser:
    path:  /tinymceBrowser/{file}
    defaults: { _controller: NyroDevUtilityBundle:Tinymce:browser, file: null }
    requirements:
        file: .+

nyrocms_admin_data:
    resource: "@NyroDevNyroCmsBundle/Resources/config/routingAdminData.yml"
    prefix:   /
