nyrocms_admin_composer:
    path:  /composer/{type}/{id}/{lang}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminComposerController::composerAction, lang: null }
    requirements:
        id: \d+

nyrocms_admin_handler_contents_add:
    path:  /handlerContents/{chid}/add
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminHandlerContentsController::addAction }
    requirements:
        chid: \d+
nyrocms_admin_handler_contents_up:
    path:  /handlerContents/{chid}/up/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminHandlerContentsController::moveAction, dir: up }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents_down:
    path:  /handlerContents/{chid}/down/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminHandlerContentsController::moveAction, dir: down }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents_edit:
    path:  /handlerContents/{chid}/edit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminHandlerContentsController::editAction }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents_delete:
    path:  /handlerContents/{chid}/delete/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminHandlerContentsController::deleteAction }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents:
    path:  /handlerContents/{chid}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminHandlerContentsController::indexAction }
    requirements:
        chid: \d+

nyrocms_admin_data_content_add:
    path:  /content/add/{pid}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentAddAction, pid: null }
    requirements:
        pid: \d+
nyrocms_admin_data_content_edit:
    path:  /content/edit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentEditAction }
    requirements:
        id: \d+
nyrocms_admin_data_content_delete:
    path:  /content/delete/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentDeleteAction }
    requirements:
        id: \d+
nyrocms_admin_data_content_fix:
    path:  /content/fix/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentFixAction, id: null }
    requirements:
        id: \d+
nyrocms_admin_data_content_tree:
    path:  /content/tree/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentTreeAction, id: null }
    requirements:
        id: \d+
nyrocms_admin_data_content:
    path:  /content
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentAction }


nyrocms_admin_data_translation_add:
    path:  /translation/add
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::translationAddAction }
nyrocms_admin_data_translation_edit:
    path:  /translation/edit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::translationEditAction }
    requirements:
        id: \d+
nyrocms_admin_data_translation_quickEdit:
    path:  /trQuickEdit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::translationEditAction, quick: true }
    requirements:
        id: \d+
nyrocms_admin_data_translation_delete:
    path:  /translation/delete/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::translationDeleteAction }
    requirements:
        id: \d+
nyrocms_admin_data_translation:
    path:  /translation
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::translationAction }
    requirements:
        page: \d+


nyrocms_admin_data_contentHandler_add:
    path:  /contentHandler/add
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentHandlerAddAction }
nyrocms_admin_data_contentHandler_edit:
    path:  /contentHandler/edit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentHandlerEditAction }
    requirements:
        id: \d+
nyrocms_admin_data_contentHandler_delete:
    path:  /contentHandler/delete/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentHandlerDeleteAction }
    requirements:
        id: \d+
nyrocms_admin_data_contentHandler:
    path:  /contentHandler
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contentHandlerAction }
    requirements:
        page: \d+


nyrocms_admin_data_contactMessage:
    path:  /contactMessage/{chid}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::contactMessageAction }
    requirements:
        chid: \d+


nyrocms_admin_data_userRole_add:
    path:  /userRole/add
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userRoleAddAction }
nyrocms_admin_data_userRole_edit:
    path:  /userRole/edit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userRoleEditAction }
    requirements:
        id: \d+
nyrocms_admin_data_userRole_delete:
    path:  /userRole/delete/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userRoleDeleteAction }
    requirements:
        id: \d+
nyrocms_admin_data_userRole:
    path:  /userRole
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userRoleAction }
    requirements:
        page: \d+


nyrocms_admin_data_user_add:
    path:  /user/add
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userAddAction }
nyrocms_admin_data_user_edit:
    path:  /user/edit/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userEditAction }
    requirements:
        id: \d+
nyrocms_admin_data_user_welcome:
    path:  /user/welcome/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userWelcomeAction }
    requirements:
        id: \d+
nyrocms_admin_data_user_delete:
    path:  /user/delete/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userDeleteAction }
    requirements:
        id: \d+
nyrocms_admin_data_user:
    path:  /user
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminDataController::userAction }
    requirements:
        page: \d+