nyrocms_admin_homepage:
    path: /
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminController::indexAction }

nyrocms_admin_login:
    path: /login
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminController::loginAction }

nyrocms_admin_forgot:
    path: /forgot/{id}/{key}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminController::forgotAction, id: null, key: null }

nyrocms_admin_welcome:
    path: /welcome/{id}/{key}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminController::forgotAction, welcome: true }

nyrocms_admin_account:
    path: /account
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminController::accountAction }

nyrocms_admin_switch_rootContent:
    path: /switchRootContent/{id}
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminTplController::switchRootContentAction }

nyrocms_admin_cc:
    path: /cc
    defaults: { _controller: NyroDev\NyroCmsBundle\Controller\AdminController::ccAction }

nyrocms_admin_security_check:
    path: /login_check

nyrocms_admin_security_logout:
    path: /logout

nyrocms_admin_tinymce_browser_dirname:
    path:  /tinymceBrowser_{dirName}/{file}
    defaults: { _controller: NyroDev\UtilityBundle\Controller\TinymceController::browserAction, file: null }
    requirements:
        file: .+

nyrocms_admin_tinymce_browser:
    path:  /tinymceBrowser/{file}
    defaults: { _controller: NyroDev\UtilityBundle\Controller\TinymceController::browserAction, file: null }
    requirements:
        file: .+

nyrocms_admin_data:
    resource: "@NyroDevNyroCmsBundle/Resources/config/routingAdminData.yaml"
    prefix:   /
