nyrocms_admin_composer:
    path:  /composer/{type}/{id}/{lang}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminComposer:composer, lang: null }
    requirements:
        id: \d+

nyrocms_admin_handler_contents_add:
    path:  /handlerContents/{chid}/add
    defaults: { _controller: NyroDevNyroCmsBundle:AdminHandlerContents:add }
    requirements:
        chid: \d+
nyrocms_admin_handler_contents_up:
    path:  /handlerContents/{chid}/up/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminHandlerContents:move, dir: up }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents_down:
    path:  /handlerContents/{chid}/down/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminHandlerContents:move, dir: down }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents_edit:
    path:  /handlerContents/{chid}/edit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminHandlerContents:edit }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents_delete:
    path:  /handlerContents/{chid}/delete/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminHandlerContents:delete }
    requirements:
        chid: \d+
        id: \d+
nyrocms_admin_handler_contents:
    path:  /handlerContents/{chid}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminHandlerContents:index }
    requirements:
        chid: \d+

nyrocms_admin_data_content_add:
    path:  /content/add/{pid}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentAdd, pid: null }
    requirements:
        pid: \d+
nyrocms_admin_data_content_edit:
    path:  /content/edit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentEdit }
    requirements:
        id: \d+
nyrocms_admin_data_content_delete:
    path:  /content/delete/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentDelete }
    requirements:
        id: \d+
nyrocms_admin_data_content_fix:
    path:  /content/fix/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentFix, id: null }
    requirements:
        id: \d+
nyrocms_admin_data_content_tree:
    path:  /content/tree/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentTree, id: null }
    requirements:
        id: \d+
nyrocms_admin_data_content:
    path:  /content
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:content }


nyrocms_admin_data_translation_add:
    path:  /translation/add
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:translationAdd }
nyrocms_admin_data_translation_edit:
    path:  /translation/edit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:translationEdit }
    requirements:
        id: \d+
nyrocms_admin_data_translation_quickEdit:
    path:  /trQuickEdit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:translationEdit, quick: true }
    requirements:
        id: \d+
nyrocms_admin_data_translation_delete:
    path:  /translation/delete/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:translationDelete }
    requirements:
        id: \d+
nyrocms_admin_data_translation:
    path:  /translation
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:translation }
    requirements:
        page: \d+


nyrocms_admin_data_contentHandler_add:
    path:  /contentHandler/add
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentHandlerAdd }
nyrocms_admin_data_contentHandler_edit:
    path:  /contentHandler/edit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentHandlerEdit }
    requirements:
        id: \d+
nyrocms_admin_data_contentHandler_delete:
    path:  /contentHandler/delete/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentHandlerDelete }
    requirements:
        id: \d+
nyrocms_admin_data_contentHandler:
    path:  /contentHandler
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:contentHandler }
    requirements:
        page: \d+


nyrocms_admin_data_userRole_add:
    path:  /userRole/add
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userRoleAdd }
nyrocms_admin_data_userRole_edit:
    path:  /userRole/edit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userRoleEdit }
    requirements:
        id: \d+
nyrocms_admin_data_userRole_delete:
    path:  /userRole/delete/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userRoleDelete }
    requirements:
        id: \d+
nyrocms_admin_data_userRole:
    path:  /userRole
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userRole }
    requirements:
        page: \d+


nyrocms_admin_data_user_add:
    path:  /user/add
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userAdd }
nyrocms_admin_data_user_edit:
    path:  /user/edit/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userEdit }
    requirements:
        id: \d+
nyrocms_admin_data_user_delete:
    path:  /user/delete/{id}
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:userDelete }
    requirements:
        id: \d+
nyrocms_admin_data_user:
    path:  /user
    defaults: { _controller: NyroDevNyroCmsBundle:AdminData:user }
    requirements:
        page: \d+