services:
    NyroDev\NyroCmsBundle\Services\NyroCmsService:
        public: true
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrocms }
    nyrocms:
        alias: NyroDev\NyroCmsBundle\Services\NyroCmsService
        public: true

    NyroDev\NyroCmsBundle\Services\UserService:
        public: true
        arguments: ['@service_container', '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface']
        tags:
          - { name: templating.helper, alias: nyrocms_user }
    nyrocms_user:
        alias: NyroDev\NyroCmsBundle\Services\UserService
        public: true

    NyroDev\NyroCmsBundle\Services\AdminService:
        public: true
        arguments: ['@service_container', '@templating.helper.assets']
        tags:
          - { name: templating.helper, alias: nyrocms_admin }
    nyrocms_admin:
        alias: NyroDev\NyroCmsBundle\Services\AdminService
        public: true

    NyroDev\NyroCmsBundle\Services\ComposerService:
        public: true
        arguments: ['@service_container', '@templating.helper.assets']
        tags:
          - { name: templating.helper, alias: nyrocms_composer }
    nyrocms_composer:
        alias: NyroDev\NyroCmsBundle\Services\ComposerService
        public: true
    
    NyroDev\NyroCmsBundle\Routing\NyrocmsLoader:
        arguments: ['@service_container']
        tags:
            - { name: routing.loader }
