services:
    NyroDev\NyroCmsBundle\Services\NyroCmsService:
        public: true
        arguments:
            - '@NyroDev\UtilityBundle\Services\NyrodevService'
            - '@NyroDev\NyroCmsBundle\Services\Db\DbAbstractService'
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
        calls:
            - [setContainerInterface, ['@service_container']]
            - [setTwig, ['@twig']]
            - [setMailerInterface, ['@mailer']]
            - [setRouteLoader, ['@nyrocms_routeLoader']]
            - [setTagRendereHelper, ['@nyrodev_tagRenderer']]
        tags:
          - { name: templating.helper, alias: nyrocms }
          - { name: kernel.event_listener, event: kernel.exception }
    nyrocms:
        alias: NyroDev\NyroCmsBundle\Services\NyroCmsService
        public: true

    NyroDev\NyroCmsBundle\Services\UserService:
        public: true
        arguments:
            - '@NyroDev\UtilityBundle\Services\NyrodevService'
            - '@NyroDev\UtilityBundle\Services\MemberService'
            - '@NyroDev\UtilityBundle\Services\FormService'
            - '@NyroDev\NyroCmsBundle\Services\Db\DbAbstractService'
            - '@NyroDev\NyroCmsBundle\Services\NyroCmsService'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
        calls:
            - [setContainerInterface, ['@service_container']]
        tags:
          - { name: templating.helper, alias: nyrocms_user }
    nyrocms_user:
        alias: NyroDev\NyroCmsBundle\Services\UserService
        public: true

    NyroDev\NyroCmsBundle\Services\AdminService:
        public: true
        arguments:
            - '@NyroDev\UtilityBundle\Services\NyrodevService'
            - '@NyroDev\UtilityBundle\Services\Db\DbAbstractService'
            - '@NyroDev\UtilityBundle\Services\MemberService'
            - '@NyroDev\NyroCmsBundle\Services\NyroCmsService'
            - '@NyroDev\NyroCmsBundle\Services\Db\DbAbstractService'
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
        calls:
            - [setContainerInterface, ['@service_container']]
            - [setAssetsPackages, ['@assets.packages']]
        tags:
          - { name: templating.helper, alias: nyrocms_admin }
    nyrocms_admin:
        alias: NyroDev\NyroCmsBundle\Services\AdminService
        public: true

    NyroDev\NyroCmsBundle\Services\ComposerService:
        public: true
        arguments:
            - '@NyroDev\UtilityBundle\Services\NyrodevService'
            - '@NyroDev\UtilityBundle\Services\ImageService'
            - '@NyroDev\NyroCmsBundle\Services\NyroCmsService'
            - '@NyroDev\NyroCmsBundle\Services\Db\DbAbstractService'
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
        calls:
            - [setContainerInterface, ['@service_container']]
            - [setAssetsPackages, ['@assets.packages']]
            - [setTwig, ['@twig']]
        tags:
          - { name: templating.helper, alias: nyrocms_composer }
    nyrocms_composer:
        alias: NyroDev\NyroCmsBundle\Services\ComposerService
        public: true

    NyroDev\NyroCmsBundle\Services\TooltipService:
        public: true
        arguments:
            - '@NyroDev\NyroCmsBundle\Services\Db\DbAbstractService'
            - '@NyroDev\NyroCmsBundle\Services\AdminService'
        calls:
            - [setTwig, ['@twig']]
        tags:
          - { name: templating.helper, alias: nyrocms_tooltip }
    nyrocms_tooltip:
        alias: NyroDev\NyroCmsBundle\Services\TooltipService
        public: true
    
    NyroDev\NyroCmsBundle\EventListener\LoginSubscriber:
        arguments:
            - '@NyroDev\NyroCmsBundle\Services\Db\DbAbstractService'
        tags:
            - { name: kernel.event_subscriber }
    
    NyroDev\NyroCmsBundle\Routing\NyroCmsLoader:
        calls:
            - [setContainerInterface, ['@service_container']]
        tags:
            - { name: routing.loader }
    nyrocms_routeLoader:
        alias: NyroDev\NyroCmsBundle\Routing\NyroCmsLoader
    
    NyroDev\NyroCmsBundle\Twig\IconExtension:
        arguments:
            - '@NyroDev\NyroCmsBundle\Services\AdminService'
        tags:
          - { name: twig.extension }