services:
    NyroDev\NyroCmsBundle\Services\Db\OrmService:
        alias: nyrocms_db:
        public: true
        arguments: ['@service_container']

    NyroDev\NyroCmsBundle\Listener\OrmListener:
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }
