services:
    NyroDev\NyroCmsBundle\Services\MainService:
        alias: nyrocms:
        public: true
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrocms }

    NyroDev\NyroCmsBundle\Services\UserService:
        alias: nyrocms_user:
        public: true
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrocms_user }

    NyroDev\NyroCmsBundle\Services\AdminService:
        alias: nyrocms_admin:
        public: true
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrocms_admin }

    NyroDev\NyroCmsBundle\Services\ComposerService:
        alias: nyrocms_composer:
        public: true
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrocms_composer }
    
    NyroDev\NyroCmsBundle\Routing\NyrocmsLoader:
        arguments: ['@service_container']
        tags:
            - { name: routing.loader }
