parameters:
    nyrocms.ormDbService.class: NyroDev\NyroCmsBundle\Services\Db\OrmService
    nyrocms.ormDbListener.class: NyroDev\NyroCmsBundle\Listener\OrmListener
    
services:
    nyrocms_db:
        class: %nyrocms.ormDbService.class%
        arguments: ['@service_container']
    nyrocms_ormListener:
        class: %nyrocms.ormDbListener.class%
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }
