parameters:
    nyrocms.mainService.class: NyroDev\NyroCmsBundle\Services\MainService
    nyrocms.userService.class: NyroDev\NyroCmsBundle\Services\UserService
    nyrocms.adminService.class: NyroDev\NyroCmsBundle\Services\AdminService
    nyrocms.composerService.class: NyroDev\NyroCmsBundle\Services\ComposerService
    nyrocms.routingLoader.class: NyroDev\NyroCmsBundle\Routing\NyrocmsLoader

services:
    nyrocms:
        class: %nyrocms.mainService.class%
        arguments: [@service_container]
        tags:
          - { name: templating.helper, alias: nyrocms }
    nyrocms_user:
        class: %nyrocms.userService.class%
        arguments: [@service_container]
        tags:
          - { name: templating.helper, alias: nyrocms_user }
    nyrocms_admin:
        class: %nyrocms.adminService.class%
        arguments: [@service_container]
        tags:
          - { name: templating.helper, alias: nyrocms_admin }
    nyrocms_composer:
        class: %nyrocms.composerService.class%
        arguments: [@service_container]
        tags:
          - { name: templating.helper, alias: nyrocms_composer }
    nyrocms.routing_loader:
        class: %nyrocms.routingLoader.class%
        arguments: [@service_container]
        tags:
            - { name: routing.loader }
