services:
    NyroDev\NyroCmsBundle\Services\NyroCmsService:
        public: true
        calls:
            - [setContainerInterface, ['@service_container']]
            - [setTwig, ['@twig']]
            - [setMailerInterface, ['@mailer']]
            - [setRouteLoader, ['@nyrocms_routeLoader']]
            - [setTagRendereHelper, ['@nyrodev_tagRenderer']]
        tags:
          - { name: templating.helper, alias: nyrocms }
          - { name: kernel.event_listener, event: kernel.exception }
    nyrocms:
        alias: NyroDev\NyroCmsBundle\Services\NyroCmsService
        public: true

    NyroDev\NyroCmsBundle\Services\UserService:
        public: true
        arguments:
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
        calls:
            - [setContainerInterface, ['@service_container']]
        tags:
          - { name: templating.helper, alias: nyrocms_user }
    nyrocms_user:
        alias: NyroDev\NyroCmsBundle\Services\UserService
        public: true

    NyroDev\NyroCmsBundle\Services\AdminService:
        public: true
        calls:
            - [setContainerInterface, ['@service_container']]
            - [setAssetsPackages, ['@assets.packages']]
        tags:
          - { name: templating.helper, alias: nyrocms_admin }
    nyrocms_admin:
        alias: NyroDev\NyroCmsBundle\Services\AdminService
        public: true

    NyroDev\NyroCmsBundle\Services\ComposerService:
        public: true
        calls:
            - [setContainerInterface, ['@service_container']]
            - [setAssetsPackages, ['@assets.packages']]
            - [setTwig, ['@twig']]
        tags:
          - { name: templating.helper, alias: nyrocms_composer }
    nyrocms_composer:
        alias: NyroDev\NyroCmsBundle\Services\ComposerService
        public: true
    
    NyroDev\NyroCmsBundle\Routing\NyroCmsLoader:
        calls:
            - [setContainerInterface, ['@service_container']]
        tags:
            - { name: routing.loader }
    nyrocms_routeLoader:
        alias: NyroDev\NyroCmsBundle\Routing\NyroCmsLoader