parameters:
    nyrocms.ormDbService.class: NyroDev\NyroCmsBundle\Services\Db\OrmService
    
services:
    nyrocms_db:
        class: %nyrocms.ormDbService.class%
        arguments: [@service_container, @nyroCms.entity_manager]
    nyrocms.entity_manager:
        class: Doctrine\ORM\EntityManager
        arguments: [%nyroCms.model_manager_name%]
