services:
    NyroDev\NyroCmsBundle\Services\Db\DbAbstractService:
        alias: NyroDev\NyroCmsBundle\Services\Db\OrmService
        public: true

    NyroDev\NyroCmsBundle\Services\Db\OrmService:
        public: true
        calls:
            - [setContainerInterface, ['@Psr\Container\ContainerInterface']]
    nyrocms_db:
        alias: NyroDev\NyroCmsBundle\Services\Db\OrmService
        public: true

    NyroDev\NyroCmsBundle\EventListener\OrmListener:
        calls:
            - [setContainerInterface, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: doctrine.event_subscriber }
