services:
    NyroDev\NyroCmsBundle\Services\Db\DbAbstractService:
        alias: NyroDev\NyroCmsBundle\Services\Db\OrmService
        public: true

    NyroDev\NyroCmsBundle\Services\Db\OrmService:
        public: true
        arguments:
            - '@NyroDev\UtilityBundle\Services\Db\DbAbstractService'
        calls:
            - [setContainerInterface, ['@service_container']]
    nyrocms_db:
        alias: NyroDev\NyroCmsBundle\Services\Db\OrmService
        public: true

    NyroDev\NyroCmsBundle\EventListener\ContentSpecSubscriber:
        arguments:
            $dbAbstractService: '@NyroDev\NyroCmsBundle\Services\Db\OrmService'
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postLoad'
                entity: 'App\Entity\ContentSpec'
